In [9]:
import pandas as pd
import numpy as np
import glob
pd.set_option('display.max_colwidth', -1)

C:\Users\Nico\AppData\Local\Temp/ipykernel_9428/800813630.py:4: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [10]:
path = r'C:/Users/Nico/Documents/repositories/crime_buenos_aires/Datasets/'

In [11]:
df_2016 = pd.read_csv(path + 'delitos_2016.csv', sep=',')
df_2017 = pd.read_csv(path + 'delitos_2017.csv', sep=',')
df_2018 = pd.read_csv(path + 'delitos_2018.csv', sep=',')
df_2019 = pd.read_csv(path + 'delitos_2019.csv', sep=',',low_memory=False)
df_2020 = pd.read_csv(path + 'delitos_2020.csv', sep=',')
df_2021 = pd.read_csv(path + 'delitos_2021.csv', sep=';')

In [12]:
df_2016.head()

id       fecha franja_horaria            tipo_delito  subtipo_delito  \
0  51585   2016-01-01  13             Robo (con violencia)   NaN              
1  83256   2016-01-01  22             Robo (con violencia)   NaN              
2  117697  2016-01-01  1              Lesiones               Siniestro Vial   
3  43088   2016-01-01  19             Hurto (sin violencia)  NaN              
4  68588   2016-01-01  4              Robo (con violencia)   Robo Automotor   

   cantidad_registrada  comuna             barrio        lat       long  
0  1.0                  9.0     Parque Avellaneda -34.648730 -58.468536  
1  1.0                  14.0    Palermo           -34.576925 -58.407400  
2  1.0                  4.0     Parque Patricios  -34.645197 -58.401099  
3  1.0                  9.0     Parque Avellaneda -34.655760 -58.478681  
4  1.0                  6.0     Caballito         -34.624128 -58.436826

In [13]:
df_2016.columns

Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')

Columnas iniciales

In [14]:
print('2016', df_2016.columns) 
print('2017', df_2017.columns)
print('2018', df_2018.columns)
print('2019', df_2019.columns)
print('2020', df_2020.columns)
print('2021', df_2021.columns)

2016 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2017 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2018 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2019 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2020 Index(['id_mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_armas', 'barrio', 'comuna', 'latitud', 'longitud', 'victimas'],
      dtype='object')
2021 Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_armas', 'barrio', 'comuna', 'latitud', 'longitud', 'cantidad

Dropeamos columnas de mas 

**2020**

In [15]:
df_2020.drop(columns=['anio', 'mes', 'dia', 'uso_armas'], inplace=True,errors='ignore')

In [16]:
df_2020.columns

Index(['id_mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'victimas'],
      dtype='object')

**2021**

In [17]:
df_2021.columns

Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_armas', 'barrio', 'comuna', 'latitud', 'longitud', 'cantidad'],
      dtype='object')

In [18]:
df_2021.drop(columns=['anio', 'mes', 'dia','uso_armas'], inplace=True,errors='ignore')

In [19]:
df_2021.columns

Index(['id-mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'cantidad'],
      dtype='object')

columnas a mantener

id, fecha, franja, tipo_delito, subtipo_delito, cantidad_registrada, barrio, comuna, latitud, longitud

Columnas luego del dropeo

In [20]:
print('2016', df_2016.columns) 
print('2017', df_2017.columns)
print('2018', df_2018.columns)
print('2019', df_2019.columns)
print('2020', df_2020.columns)
print('2021', df_2021.columns)

2016 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2017 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2018 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2019 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2020 Index(['id_mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'victimas'],
      dtype='object')
2021 Index(['id-mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'cantidad'],
      dtype='object')


Cambiamos nombres de las columnas

In [21]:
df_2020.rename(columns={'id_mapa':'id','franja':'franja_horaria',
                        'tipo':'tipo_delito','subtipo':'subtipo_delito',
                        'victimas':'cantidad_registrada','latitud':'lat',
                        'longitud':'long'}, inplace=True)

In [22]:
df_2021.rename(columns={'id-mapa':'id','franja':'franja_horaria',
                        'tipo':'tipo_delito','subtipo':'subtipo_delito',
                        'cantidad':'cantidad_registrada','latitud':'lat',
                        'longitud':'long'}, inplace=True)

Columnas finales

In [23]:
print('2016', df_2016.columns) 
print('2017', df_2017.columns)
print('2018', df_2018.columns)
print('2019', df_2019.columns)
print('2020', df_2020.columns)
print('2021', df_2021.columns)

2016 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2017 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2018 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2019 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2020 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'barrio', 'comuna', 'lat', 'long', 'cantidad_registrada'],
      dtype='object')
2021 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'barrio', 'comuna', 'lat', 'long', 'cantidad_registrada'],
      dtype='object')


## Fechas

In [24]:
df_2016['fecha'] = pd.to_datetime(df_2016['fecha'], format='%Y-%m-%d')
df_2017['fecha'] = pd.to_datetime(df_2017['fecha'], format='%Y-%m-%d')
df_2018['fecha'] = pd.to_datetime(df_2018['fecha'], format='%Y-%m-%d')

In [25]:
df_2019['fecha'] = pd.to_datetime(df_2019['fecha'], format='%d-%m-%y').dt.strftime('%Y-%m-%d')

In [26]:
df_2020['fecha'] = pd.to_datetime(df_2020['fecha'], format='%d/%m/%y').dt.strftime('%Y-%m-%d')

In [27]:
df_2021['fecha'] = pd.to_datetime(df_2021['fecha'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')

## Franja horaria
    Exploramos columnas franja horaria (ideal seria que este en formato str)

In [28]:
df_2019['franja_horaria'] = df_2019['franja_horaria'].astype(str)

In [29]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    dataframe.drop(dataframe[(dataframe['franja_horaria'] == 'S/D') | (dataframe['franja_horaria'] == 'SD') |  (dataframe['franja_horaria'] == 'sd')].index, inplace=True)

## Tipo Delito

In [30]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['tipo_delito'].unique())

array(['Robo (con violencia)', 'Lesiones', 'Hurto (sin violencia)',
       'Homicidio'], dtype=object)

array(['Robo (con violencia)', 'Hurto (sin violencia)', 'Lesiones',
       'Homicidio'], dtype=object)

array(['Hurto (sin violencia)', 'Robo (con violencia)', 'Homicidio',
       'Lesiones'], dtype=object)

array(['Robo (con violencia)', 'Hurto (sin violencia)', 'Homicidio',
       'Lesiones'], dtype=object)

array(['Hurto (sin violencia)', 'Homicidio', 'Robo (con violencia)',
       'Lesiones'], dtype=object)

array(['Homicidio', 'Lesiones', 'Robo (con violencia)',
       'Hurto (sin violencia)'], dtype=object)

## Subtipo Delito

In [31]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['subtipo_delito'].unique())

array([nan, 'Siniestro Vial', 'Robo Automotor', 'Hurto Automotor',
       'Doloso'], dtype=object)

array([nan, 'Hurto Automotor', 'Robo Automotor', 'Siniestro Vial',
       'Doloso'], dtype=object)

array([nan, 'Hurto Automotor', 'Robo Automotor', 'Siniestro Vial',
       'Doloso'], dtype=object)

array([nan, 'Hurto Automotor', 'Doloso', 'Siniestro Vial',
       'Robo Automotor'], dtype=object)

array([nan, 'Femicidio', 'Siniestro Vial', 'Con uso de moto',
       'Hurto Automotor', 'Robo Automotor', 'Doloso',
       'Femicidio Intrafamiliar', 'Travesticidio/Transfemicidio'],
      dtype=object)

array(['Siniestro Vial', 'Doloso', 'Femicidio', nan, 'Robo Automotor',
       'Hurto Automotor', 'Con uso de moto'], dtype=object)

In [32]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe.groupby(['tipo_delito']).agg({'subtipo_delito':'unique'}).reset_index())

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [nan]                   
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito  \
0  Homicidio               
1  Hurto (sin violencia)   
2  Lesiones                
3  Robo (con violencia)    

                                                                               subtipo_delito  
0  [Femicidio, Siniestro Vial, Doloso, Femicidio Intrafamiliar, Travesticidio/Transfemicidio]  
1  [nan, Hurto Automotor]                                                                      
2  [Siniestro Vial]                                                                            
3  [nan, Con uso de moto, Robo Automotor]

tipo_delito                          subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso, Femicidio]   
1  Hurto (sin violencia)  [nan, Hurto Automotor]                
2  Lesiones               [Siniestro Vial]                      
3  Robo (con violencia)   [nan, Robo Automotor, Con uso de moto]

In [33]:
df_2019.loc[df_2019['tipo_delito']=='Lesiones', 'subtipo_delito'] = 'Siniestro Vial'

df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Travesticidio/Transfemicidio','Doloso')
df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Femicidio Intrafamiliar','Doloso')
df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Femicidio','Doloso')
df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Con uso de moto',np.nan)

df_2021['subtipo_delito'] = df_2021['subtipo_delito'].replace('Femicidio','Doloso')
df_2021['subtipo_delito'] = df_2021['subtipo_delito'].replace('Con uso de moto',np.nan)


Unificamos los datos de subtipo de lesiones

In [34]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe.groupby(['tipo_delito']).agg({'subtipo_delito':'unique'}).reset_index())

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

## Barrio

eliminamos todos los nan

In [35]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    dataframe.drop(dataframe[(dataframe['barrio'].isna())].index, inplace=True)

## Comuna

los valores van del 1 al 15

In [36]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['comuna'].unique())
    

array([ 9., 14.,  4.,  6.,  1.,  3., 10.,  8., 11.,  7.,  2., 12., 13.,
        5., 15.])

array([ 6.,  1.,  4., 14., 11., 13.,  7., 15.,  3.,  9., 12.,  8.,  5.,
        2., 10.])

array([10.,  8., 13.,  4.,  1.,  3., 14., 15.,  2., 12.,  9., 11.,  7.,
        5.,  6.])

array([ 6.,  3.,  1., 11., 15.,  5.,  2., 14., 13., 12.,  8.,  9.,  4.,
        7., 10.])

array([10., 11.,  9., 12., 15.,  8., 13.,  7.,  6., 14.,  5.,  4.,  3.,
        2.,  1.])

array([ 1.,  9.,  7.,  5., 14., 15.,  4.,  6., 12.,  2.,  8., 10.,  3.,
       13., 11.])

## ID

In [37]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['id'].unique())

array([ 51585,  83256, 117697, ...,  79693,  81292,  81314], dtype=int64)

array([178852, 132140, 189963, ..., 243798, 243802, 243801], dtype=int64)

array([269335, 248498, 248172, ..., 367224, 367223, 360640], dtype=int64)

array([1038983, 1038986, 1038989, ..., 1038975, 1038977, 1038982],
      dtype=int64)

array(['RH-2020-0000480', 'HD-2020-0001119', 'RH-2020-0001140', ...,
       'RH-2020-0684431', 'RH-2021-0004353', 'RH-2020-0684320'],
      dtype=object)

array(['HC-2021-1008202', 'HC-2021-1009094', 'HC-2021-1013236', ...,
       'RH-2021-3768589', 'RH-2021-3783716', 'RH-2021-3807019'],
      dtype=object)

## Unimos los datasets

In [38]:
df = pd.concat([df_2016, df_2017, df_2018, df_2019, df_2020, df_2021])

In [39]:
df.columns

Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')

In [40]:
df['barrio'].unique()

array(['Parque Avellaneda', 'Palermo', 'Parque Patricios', 'Caballito',
       'Monserrat', 'Barracas', 'Mataderos', 'Balvanera', 'Constitución',
       'Floresta', 'Villa Soldati', 'Villa Devoto', 'Flores', 'Boca',
       'San Cristóbal', 'Recoleta', 'San Nicolás', 'Villa Santa Rita',
       'Villa Pueyrredón', 'Monte Castro', 'Liniers', 'Vélez Sársfield',
       'Villa Urquiza', 'Versalles', 'Colegiales', 'Retiro',
       'Nueva Pompeya', 'Nuñez', 'Boedo', 'San Telmo', 'Almagro',
       'Villa Real', 'Villa Luro', 'Coghlan', 'Villa Lugano',
       'Villa Gral. Mitre', 'Villa Riachuelo', 'Parque Chacabuco',
       'Chacarita', 'Belgrano', 'Villa del Parque', 'Saavedra',
       'Paternal', 'Villa Crespo', 'Villa Ortuzar', 'Parque Chas',
       'Agronomía', 'Puerto Madero', 'Villa Del Parque', 'La Boca',
       'Nueva pompeya'], dtype=object)

In [41]:
df['fecha'] = pd.to_datetime(df['fecha'], format='%Y-%m-%d')

In [42]:
df.head()

id      fecha franja_horaria            tipo_delito  subtipo_delito  \
0  51585  2016-01-01  13             Robo (con violencia)   NaN              
1  83256  2016-01-01  22             Robo (con violencia)   NaN              
2  117697 2016-01-01  1              Lesiones               Siniestro Vial   
3  43088  2016-01-01  19             Hurto (sin violencia)  NaN              
4  68588  2016-01-01  4              Robo (con violencia)   Robo Automotor   

   cantidad_registrada  comuna             barrio        lat       long  
0  1.0                  9.0     Parque Avellaneda -34.64873  -58.468536  
1  1.0                  14.0    Palermo           -34.576925 -58.4074    
2  1.0                  4.0     Parque Patricios  -34.645197 -58.401099  
3  1.0                  9.0     Parque Avellaneda -34.65576  -58.478681  
4  1.0                  6.0     Caballito         -34.624128 -58.436826

In [43]:
df['comuna'].unique()

array([ 9., 14.,  4.,  6.,  1.,  3., 10.,  8., 11.,  7.,  2., 12., 13.,
        5., 15.])

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 636598 entries, 0 to 88566
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype         
---  ------               --------------   -----         
 0   id                   636598 non-null  object        
 1   fecha                636598 non-null  datetime64[ns]
 2   franja_horaria       636598 non-null  object        
 3   tipo_delito          636598 non-null  object        
 4   subtipo_delito       91169 non-null   object        
 5   cantidad_registrada  379844 non-null  float64       
 6   comuna               636598 non-null  float64       
 7   barrio               636598 non-null  object        
 8   lat                  636598 non-null  object        
 9   long                 636598 non-null  object        
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 53.4+ MB


In [45]:
df.groupby(['tipo_delito']).agg({'subtipo_delito':'unique'}).reset_index()

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

## Cambios implementados: 

- Se eliminaron las filas con 'franja_horaria' = 'S/D', 'SD', 'sd'. Aprox 2100 filas
- Se eliminaron las filas con 'barrio' = nan
- En subtipo de lesiones se unificaron los datos. Por ejemplo se paso los femicidios a homicidio doloso, porque solo hay datos de femicidios de un solo año, lo mismo con los transvesticidios. Los robos con moto se los pone como roobo con violencia, etc
