In [1]:
import pandas as pd
import numpy as np
import xlsxwriter
pd.set_option('display.max_colwidth', -1)

C:\Users\Nico\AppData\Local\Temp/ipykernel_25100/3430237162.py:4: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)


In [2]:
path = r'C:/Users/Nico/Documents/repositories/crime_buenos_aires/Datasets/'

In [3]:
df_2016 = pd.read_csv(path + 'delitos_2016.csv', sep=',')
df_2017 = pd.read_csv(path + 'delitos_2017.csv', sep=',')
df_2018 = pd.read_csv(path + 'delitos_2018.csv', sep=',')
df_2019 = pd.read_csv(path + 'delitos_2019.csv', sep=',',low_memory=False)
df_2020 = pd.read_csv(path + 'delitos_2020.csv', sep=',')
df_2021 = pd.read_csv(path + 'delitos_2021.csv', sep=';')

In [4]:
df_2016.head()

id       fecha franja_horaria            tipo_delito  subtipo_delito  \
0  51585   2016-01-01  13             Robo (con violencia)   NaN              
1  83256   2016-01-01  22             Robo (con violencia)   NaN              
2  117697  2016-01-01  1              Lesiones               Siniestro Vial   
3  43088   2016-01-01  19             Hurto (sin violencia)  NaN              
4  68588   2016-01-01  4              Robo (con violencia)   Robo Automotor   

   cantidad_registrada  comuna             barrio        lat       long  
0  1.0                  9.0     Parque Avellaneda -34.648730 -58.468536  
1  1.0                  14.0    Palermo           -34.576925 -58.407400  
2  1.0                  4.0     Parque Patricios  -34.645197 -58.401099  
3  1.0                  9.0     Parque Avellaneda -34.655760 -58.478681  
4  1.0                  6.0     Caballito         -34.624128 -58.436826

In [5]:
df_2016.columns

Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')

Columnas iniciales

In [6]:
print('2016', df_2016.columns) 
print('2017', df_2017.columns)
print('2018', df_2018.columns)
print('2019', df_2019.columns)
print('2020', df_2020.columns)
print('2021', df_2021.columns)

2016 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2017 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2018 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2019 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2020 Index(['id_mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_armas', 'barrio', 'comuna', 'latitud', 'longitud', 'victimas'],
      dtype='object')
2021 Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_armas', 'barrio', 'comuna', 'latitud', 'longitud', 'cantidad

Dropeamos columnas de mas 

**2020**

In [7]:
df_2020.drop(columns=['anio', 'mes', 'dia', 'uso_armas'], inplace=True,errors='ignore')

In [8]:
df_2020.columns

Index(['id_mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'victimas'],
      dtype='object')

**2021**

In [9]:
df_2021.columns

Index(['id-mapa', 'anio', 'mes', 'dia', 'fecha', 'franja', 'tipo', 'subtipo',
       'uso_armas', 'barrio', 'comuna', 'latitud', 'longitud', 'cantidad'],
      dtype='object')

In [10]:
df_2021.drop(columns=['anio', 'mes', 'dia','uso_armas'], inplace=True,errors='ignore')

In [11]:
df_2021.columns

Index(['id-mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'cantidad'],
      dtype='object')

columnas a mantener

id, fecha, franja, tipo_delito, subtipo_delito, cantidad_registrada, barrio, comuna, latitud, longitud

Columnas luego del dropeo

In [12]:
print('2016', df_2016.columns) 
print('2017', df_2017.columns)
print('2018', df_2018.columns)
print('2019', df_2019.columns)
print('2020', df_2020.columns)
print('2021', df_2021.columns)

2016 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2017 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2018 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2019 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2020 Index(['id_mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'victimas'],
      dtype='object')
2021 Index(['id-mapa', 'fecha', 'franja', 'tipo', 'subtipo', 'barrio', 'comuna',
       'latitud', 'longitud', 'cantidad'],
      dtype='object')


Cambiamos nombres de las columnas

In [13]:
df_2020.rename(columns={'id_mapa':'id','franja':'franja_horaria',
                        'tipo':'tipo_delito','subtipo':'subtipo_delito',
                        'victimas':'cantidad_registrada','latitud':'lat',
                        'longitud':'long'}, inplace=True)

In [14]:
df_2021.rename(columns={'id-mapa':'id','franja':'franja_horaria',
                        'tipo':'tipo_delito','subtipo':'subtipo_delito',
                        'cantidad':'cantidad_registrada','latitud':'lat',
                        'longitud':'long'}, inplace=True)

Columnas finales

In [15]:
print('2016', df_2016.columns) 
print('2017', df_2017.columns)
print('2018', df_2018.columns)
print('2019', df_2019.columns)
print('2020', df_2020.columns)
print('2021', df_2021.columns)

2016 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2017 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2018 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2019 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'cantidad_registrada', 'comuna', 'barrio', 'lat', 'long'],
      dtype='object')
2020 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'barrio', 'comuna', 'lat', 'long', 'cantidad_registrada'],
      dtype='object')
2021 Index(['id', 'fecha', 'franja_horaria', 'tipo_delito', 'subtipo_delito',
       'barrio', 'comuna', 'lat', 'long', 'cantidad_registrada'],
      dtype='object')


## Fechas

In [16]:
df_2016['fecha'] = pd.to_datetime(df_2016['fecha'], format='%Y-%m-%d')
df_2017['fecha'] = pd.to_datetime(df_2017['fecha'], format='%Y-%m-%d')
df_2018['fecha'] = pd.to_datetime(df_2018['fecha'], format='%Y-%m-%d')

In [17]:
df_2019['fecha'] = pd.to_datetime(df_2019['fecha'], format='%d-%m-%y').dt.strftime('%Y-%m-%d')

In [18]:
df_2020['fecha'] = pd.to_datetime(df_2020['fecha'], format='%d/%m/%y').dt.strftime('%Y-%m-%d')

In [19]:
df_2021['fecha'] = pd.to_datetime(df_2021['fecha'], format='%d/%m/%Y').dt.strftime('%Y-%m-%d')

## Franja horaria
    Exploramos columnas franja horaria (ideal seria que este en formato str)

In [20]:
df_2019['franja_horaria'] = df_2019['franja_horaria'].astype(str)

In [21]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    dataframe.drop(dataframe[(dataframe['franja_horaria'] == 'S/D') | (dataframe['franja_horaria'] == 'SD') |  (dataframe['franja_horaria'] == 'sd')].index, inplace=True)

## Tipo Delito

In [22]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['tipo_delito'].unique())

array(['Robo (con violencia)', 'Lesiones', 'Hurto (sin violencia)',
       'Homicidio'], dtype=object)

array(['Robo (con violencia)', 'Hurto (sin violencia)', 'Lesiones',
       'Homicidio'], dtype=object)

array(['Hurto (sin violencia)', 'Robo (con violencia)', 'Homicidio',
       'Lesiones'], dtype=object)

array(['Robo (con violencia)', 'Hurto (sin violencia)', 'Homicidio',
       'Lesiones'], dtype=object)

array(['Hurto (sin violencia)', 'Homicidio', 'Robo (con violencia)',
       'Lesiones'], dtype=object)

array(['Homicidio', 'Lesiones', 'Robo (con violencia)',
       'Hurto (sin violencia)'], dtype=object)

## Subtipo Delito

In [23]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['subtipo_delito'].unique())

array([nan, 'Siniestro Vial', 'Robo Automotor', 'Hurto Automotor',
       'Doloso'], dtype=object)

array([nan, 'Hurto Automotor', 'Robo Automotor', 'Siniestro Vial',
       'Doloso'], dtype=object)

array([nan, 'Hurto Automotor', 'Robo Automotor', 'Siniestro Vial',
       'Doloso'], dtype=object)

array([nan, 'Hurto Automotor', 'Doloso', 'Siniestro Vial',
       'Robo Automotor'], dtype=object)

array([nan, 'Femicidio', 'Siniestro Vial', 'Con uso de moto',
       'Hurto Automotor', 'Robo Automotor', 'Doloso',
       'Femicidio Intrafamiliar', 'Travesticidio/Transfemicidio'],
      dtype=object)

array(['Siniestro Vial', 'Doloso', 'Femicidio', nan, 'Robo Automotor',
       'Hurto Automotor', 'Con uso de moto'], dtype=object)

In [24]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe.groupby(['tipo_delito']).agg({'subtipo_delito':'unique'}).reset_index())

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [nan]                   
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito  \
0  Homicidio               
1  Hurto (sin violencia)   
2  Lesiones                
3  Robo (con violencia)    

                                                                               subtipo_delito  
0  [Femicidio, Siniestro Vial, Doloso, Femicidio Intrafamiliar, Travesticidio/Transfemicidio]  
1  [nan, Hurto Automotor]                                                                      
2  [Siniestro Vial]                                                                            
3  [nan, Con uso de moto, Robo Automotor]

tipo_delito                          subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso, Femicidio]   
1  Hurto (sin violencia)  [nan, Hurto Automotor]                
2  Lesiones               [Siniestro Vial]                      
3  Robo (con violencia)   [nan, Robo Automotor, Con uso de moto]

In [25]:
df_2019.loc[df_2019['tipo_delito']=='Lesiones', 'subtipo_delito'] = 'Siniestro Vial'

df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Travesticidio/Transfemicidio','Doloso')
df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Femicidio Intrafamiliar','Doloso')
df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Femicidio','Doloso')
df_2020['subtipo_delito'] = df_2020['subtipo_delito'].replace('Con uso de moto',np.nan)

df_2021['subtipo_delito'] = df_2021['subtipo_delito'].replace('Femicidio','Doloso')
df_2021['subtipo_delito'] = df_2021['subtipo_delito'].replace('Con uso de moto',np.nan)


Unificamos los datos de subtipo de lesiones

In [26]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe.groupby(['tipo_delito']).agg({'subtipo_delito':'unique'}).reset_index())

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

tipo_delito            subtipo_delito
0  Homicidio              [Siniestro Vial, Doloso]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

## Barrio

eliminamos todos los nan

In [27]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    dataframe.drop(dataframe[(dataframe['barrio'].isna())].index, inplace=True)

## Comuna

los valores van del 1 al 15

In [28]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['comuna'].unique())
    

array([ 9., 14.,  4.,  6.,  1.,  3., 10.,  8., 11.,  7.,  2., 12., 13.,
        5., 15.])

array([ 6.,  1.,  4., 14., 11., 13.,  7., 15.,  3.,  9., 12.,  8.,  5.,
        2., 10.])

array([10.,  8., 13.,  4.,  1.,  3., 14., 15.,  2., 12.,  9., 11.,  7.,
        5.,  6.])

array([ 6.,  3.,  1., 11., 15.,  5.,  2., 14., 13., 12.,  8.,  9.,  4.,
        7., 10.])

array([10., 11.,  9., 12., 15.,  8., 13.,  7.,  6., 14.,  5.,  4.,  3.,
        2.,  1.])

array([ 1.,  9.,  7.,  5., 14., 15.,  4.,  6., 12.,  2.,  8., 10.,  3.,
       13., 11.])

## ID

In [29]:
dataframes = [df_2016, df_2017, df_2018, df_2019, df_2020, df_2021]

for dataframe in dataframes:
    display(dataframe['id'].unique())

array([ 51585,  83256, 117697, ...,  79693,  81292,  81314], dtype=int64)

array([178852, 132140, 189963, ..., 243798, 243802, 243801], dtype=int64)

array([269335, 248498, 248172, ..., 367224, 367223, 360640], dtype=int64)

array([1038983, 1038986, 1038989, ..., 1038975, 1038977, 1038982],
      dtype=int64)

array(['RH-2020-0000480', 'HD-2020-0001119', 'RH-2020-0001140', ...,
       'RH-2020-0684431', 'RH-2021-0004353', 'RH-2020-0684320'],
      dtype=object)

array(['HC-2021-1008202', 'HC-2021-1009094', 'HC-2021-1013236', ...,
       'RH-2021-3768589', 'RH-2021-3783716', 'RH-2021-3807019'],
      dtype=object)

## Unimos los datasets

In [30]:
df = pd.concat([df_2016, df_2017, df_2018, df_2019, df_2020, df_2021])

In [31]:
df.head()

id                fecha franja_horaria            tipo_delito  \
0  51585   2016-01-01 00:00:00  13             Robo (con violencia)    
1  83256   2016-01-01 00:00:00  22             Robo (con violencia)    
2  117697  2016-01-01 00:00:00  1              Lesiones                
3  43088   2016-01-01 00:00:00  19             Hurto (sin violencia)   
4  68588   2016-01-01 00:00:00  4              Robo (con violencia)    

   subtipo_delito  cantidad_registrada  comuna             barrio        lat  \
0  NaN             1.0                  9.0     Parque Avellaneda -34.64873    
1  NaN             1.0                  14.0    Palermo           -34.576925   
2  Siniestro Vial  1.0                  4.0     Parque Patricios  -34.645197   
3  NaN             1.0                  9.0     Parque Avellaneda -34.65576    
4  Robo Automotor  1.0                  6.0     Caballito         -34.624128   

        long  
0 -58.468536  
1 -58.4074    
2 -58.401099  
3 -58.478681  
4 -58.436826

In [32]:
# Se observan 2 'Villa del Parque', reemplazamos para dejar solo uno
df['barrio'] = df['barrio'].replace('Villa Del Parque','Villa del Parque')
df['barrio'] = df['barrio'].replace('Boca','La Boca')
df['barrio'] = df['barrio'].replace('Paternal','La Paternal')
df['barrio'] = df['barrio'].replace('Nueva pompeya','Nueva Pompeya')

In [33]:
df['barrio'].unique()

array(['Parque Avellaneda', 'Palermo', 'Parque Patricios', 'Caballito',
       'Monserrat', 'Barracas', 'Mataderos', 'Balvanera', 'Constitución',
       'Floresta', 'Villa Soldati', 'Villa Devoto', 'Flores', 'La Boca',
       'San Cristóbal', 'Recoleta', 'San Nicolás', 'Villa Santa Rita',
       'Villa Pueyrredón', 'Monte Castro', 'Liniers', 'Vélez Sársfield',
       'Villa Urquiza', 'Versalles', 'Colegiales', 'Retiro',
       'Nueva Pompeya', 'Nuñez', 'Boedo', 'San Telmo', 'Almagro',
       'Villa Real', 'Villa Luro', 'Coghlan', 'Villa Lugano',
       'Villa Gral. Mitre', 'Villa Riachuelo', 'Parque Chacabuco',
       'Chacarita', 'Belgrano', 'Villa del Parque', 'Saavedra',
       'La Paternal', 'Villa Crespo', 'Villa Ortuzar', 'Parque Chas',
       'Agronomía', 'Puerto Madero'], dtype=object)

### Creamos la tabla **COMUNAS**

In [34]:
comunas = pd.DataFrame(data={'id_comuna':np.arange(1,16),'nombre_comuna':['Retiro, San Nicolás, Puerto Madero, San Telmo, Monserrat y Constitución',
                                                                'Recoleta',
                                                                'Balvanera y San Cristóbal',
                                                                'La Boca, Barracas, Parque Patricios y Nueva Pompeya',
                                                                'Almagro y Boedo',
                                                               'Caballito',
                                                               'Flores y Parque Chacabuco',
                                                               'Villa Soldati, Villa Riachuelo y Villa Lugano',
                                                               'Liniers, Mataderos y Parque Avellaneda',
                                                               'Villa Real, Monte Castro, Versalles, Floresta, Vélez Sársfield y Villa Luro',
                                                               'Villa Gral. Mitre, Villa Devoto, Villa del Parque y Villa Santa Rita',
                                                               'Coghlan, Saavedra, Villa Urquiza y Villa Pueyrredón',
                                                               'Nuñez, Belgrano y Colegiales',
                                                               'Palermo',
                                                               'Chacarita, Villa Crespo, La Paternal, Villa Ortuzar, Agronomía y Parque Chas']})

In [35]:
comunas

id_comuna  \
0   1           
1   2           
2   3           
3   4           
4   5           
5   6           
6   7           
7   8           
8   9           
9   10          
10  11          
11  12          
12  13          
13  14          
14  15          

                                                                   nombre_comuna  
0   Retiro, San Nicolás, Puerto Madero, San Telmo, Monserrat y Constitución       
1   Recoleta                                                                      
2   Balvanera y San Cristóbal                                                     
3   La Boca, Barracas, Parque Patricios y Nueva Pompeya                           
4   Almagro y Boedo                                                               
5   Caballito                                                                     
6   Flores y Parque Chacabuco                                                     
7   Villa Soldati, Villa Riachuelo y Villa Lugano                                 
8   Liniers, Mataderos y Parque Avellaneda                                        
9   Villa Real, Monte Castro, Versalles, Floresta, Vélez Sársfield y Villa Luro   
10  Villa Gral. Mitre, Villa Devoto, Villa del Parque y Villa Santa Rita          
11  Coghlan, Saavedra, Villa Urquiza y Villa Pueyrredón                           
12  Nuñez, Belgrano y Colegiales                                                  
13  Palermo                                                                       
14  Chacarita, Villa Crespo, La Paternal, Villa Ortuzar, Agronomía y Parque Chas

### Creamos tabla **BARRIOS**

In [36]:
df['barrio'].unique()

array(['Parque Avellaneda', 'Palermo', 'Parque Patricios', 'Caballito',
       'Monserrat', 'Barracas', 'Mataderos', 'Balvanera', 'Constitución',
       'Floresta', 'Villa Soldati', 'Villa Devoto', 'Flores', 'La Boca',
       'San Cristóbal', 'Recoleta', 'San Nicolás', 'Villa Santa Rita',
       'Villa Pueyrredón', 'Monte Castro', 'Liniers', 'Vélez Sársfield',
       'Villa Urquiza', 'Versalles', 'Colegiales', 'Retiro',
       'Nueva Pompeya', 'Nuñez', 'Boedo', 'San Telmo', 'Almagro',
       'Villa Real', 'Villa Luro', 'Coghlan', 'Villa Lugano',
       'Villa Gral. Mitre', 'Villa Riachuelo', 'Parque Chacabuco',
       'Chacarita', 'Belgrano', 'Villa del Parque', 'Saavedra',
       'La Paternal', 'Villa Crespo', 'Villa Ortuzar', 'Parque Chas',
       'Agronomía', 'Puerto Madero'], dtype=object)

In [37]:
lista_barrios = df['barrio'].unique().tolist()

barrios = pd.DataFrame(data={'id_barrio':np.arange(1,49),'nombre_barrio':lista_barrios})

In [38]:
barrios['id_comuna'] =""

for barrio in lista_barrios:
    for comuna in comunas['nombre_comuna']:
        if barrio in comuna:
            value = comunas.loc[comunas['nombre_comuna'] == comuna]['id_comuna'].values[0]
            barrios.loc[barrios['nombre_barrio'] == barrio, 'id_comuna'] = value


In [39]:
barrios

id_barrio      nombre_barrio id_comuna
0   1          Parque Avellaneda  9       
1   2          Palermo            14      
2   3          Parque Patricios   4       
3   4          Caballito          6       
4   5          Monserrat          1       
5   6          Barracas           4       
6   7          Mataderos          9       
7   8          Balvanera          3       
8   9          Constitución       1       
9   10         Floresta           10      
10  11         Villa Soldati      8       
11  12         Villa Devoto       11      
12  13         Flores             10      
13  14         La Boca            4       
14  15         San Cristóbal      3       
15  16         Recoleta           2       
16  17         San Nicolás        1       
17  18         Villa Santa Rita   11      
18  19         Villa Pueyrredón   12      
19  20         Monte Castro       10      
20  21         Liniers            9       
21  22         Vélez Sársfield    10      
22  23         Villa Urquiza      12      
23  24         Versalles          10      
24  25         Colegiales         13      
25  26         Retiro             1       
26  27         Nueva Pompeya      4       
27  28         Nuñez              13      
28  29         Boedo              5       
29  30         San Telmo          1       
30  31         Almagro            5       
31  32         Villa Real         10      
32  33         Villa Luro         10      
33  34         Coghlan            12      
34  35         Villa Lugano       8       
35  36         Villa Gral. Mitre  11      
36  37         Villa Riachuelo    8       
37  38         Parque Chacabuco   7       
38  39         Chacarita          15      
39  40         Belgrano           13      
40  41         Villa del Parque   11      
41  42         Saavedra           12      
42  43         La Paternal        15      
43  44         Villa Crespo       15      
44  45         Villa Ortuzar      15      
45  46         Parque Chas        15      
46  47         Agronomía          15      
47  48         Puerto Madero      1

### Creamos tabla **TIPO DELITO**

In [40]:
df.groupby(['tipo_delito']).agg({'subtipo_delito':'unique'}).reset_index()

tipo_delito            subtipo_delito
0  Homicidio              [Doloso, Siniestro Vial]
1  Hurto (sin violencia)  [nan, Hurto Automotor]  
2  Lesiones               [Siniestro Vial]        
3  Robo (con violencia)   [nan, Robo Automotor]

Para la tabla tipo delito unificamos las columnas 'tipo delito' y 'subtipo delito' creando una columna llamada delito que luego sera una tabla

In [41]:
df['delito'] = ""

df.loc[(df['tipo_delito'] == 'Homicidio')&(df['subtipo_delito'] == 'Doloso'), 'delito'] = 'Homicidio Doloso'
df.loc[(df['tipo_delito'] == 'Homicidio')&(df['subtipo_delito'] == 'Siniestro Vial'), 'delito'] = 'Homicidio Siniestro Vial'
df.loc[(df['tipo_delito'] == 'Hurto (sin violencia)')&(df['subtipo_delito'].isna()), 'delito'] = 'Hurto'
df.loc[(df['tipo_delito'] == 'Hurto (sin violencia)')&(df['subtipo_delito']== 'Hurto Automotor'), 'delito'] = 'Hurto Automotor'
df.loc[(df['tipo_delito'] == 'Lesiones')&(df['subtipo_delito']== 'Siniestro Vial'), 'delito'] = 'Lesiones Siniestro Vial'
df.loc[(df['tipo_delito'] == 'Robo (con violencia)')&(df['subtipo_delito'].isna()), 'delito'] = 'Robo'
df.loc[(df['tipo_delito'] == 'Robo (con violencia)')&(df['subtipo_delito']=='Robo Automotor'), 'delito'] = 'Robo Automotor'

In [42]:
df['delito'].unique()

array(['Robo', 'Lesiones Siniestro Vial', 'Hurto', 'Robo Automotor',
       'Hurto Automotor', 'Homicidio Doloso', 'Homicidio Siniestro Vial'],
      dtype=object)

In [43]:
delitos = pd.DataFrame(data={'id_delito':np.arange(1,8),
                             'nombre_delito':['Robo', 'Lesiones Siniestro Vial', 'Hurto', 'Robo Automotor',
                             'Hurto Automotor', 'Homicidio Doloso', 'Homicidio Siniestro Vial'],
                             'descripcion_delito':['Apoderarse ilegítimamente de un bien ajeno, a través de la fuerza en las cosas o violencia en las personas',
                                                    'Siniestro vial, cuya víctima resulta en lesiones (y no resulte fallecida en el acto o hasta 30 días después del hecho)',
                                                    'Apoderarse ilegítimamente de un bien ajeno, sin el uso de fuerza en las cosas o violencia en las personas',
                                                    'Apoderarse de un vehículo (rodado) completo, con motor y 4 o más ruedas; a través de la fuerza en las cosas o violencia en las personas',
                                                    'Apoderarse de un vehículo (rodado) completo, con motor y 4 o más ruedas; sin el uso de fuerza en las cosas o violencia en las personas',
                                                    'Muerte violenta según art. 79 C.P',
                                                    'Siniestro víal cuya victima resulta en fallecimiento (en el acto o hasta 30 días después del hecho)']})
                                                                                            

In [44]:
delitos

id_delito             nombre_delito  \
0  1          Robo                       
1  2          Lesiones Siniestro Vial    
2  3          Hurto                      
3  4          Robo Automotor             
4  5          Hurto Automotor            
5  6          Homicidio Doloso           
6  7          Homicidio Siniestro Vial   

                                                                                                                        descripcion_delito  
0  Apoderarse ilegítimamente de un bien ajeno, a través de la fuerza en las cosas o violencia en las personas                               
1  Siniestro vial, cuya víctima resulta en lesiones (y no resulte fallecida en el acto o hasta 30 días después del hecho)                   
2  Apoderarse ilegítimamente de un bien ajeno, sin el uso de fuerza en las cosas o violencia en las personas                                
3  Apoderarse de un vehículo (rodado) completo, con motor y 4 o más ruedas; a través de la fuerza en las cosas o violencia en las personas  
4  Apoderarse de un vehículo (rodado) completo, con motor y 4 o más ruedas; sin el uso de fuerza en las cosas o violencia en las personas   
5  Muerte violenta según art. 79 C.P                                                                                                        
6  Siniestro víal cuya victima resulta en fallecimiento (en el acto o hasta 30 días después del hecho)

### Fecha

In [45]:
df['fecha'] = pd.to_datetime(df['fecha'], format='%Y-%m-%d')

## Datasets Finales

Los dataset finales son 5:
- main
- barrios
- delitos
- comunas
- fecha

In [46]:
main = df.copy()

In [47]:
main.drop(columns=['tipo_delito','subtipo_delito','cantidad_registrada'],inplace=True)

In [48]:
main.rename(columns={'id':'id_legajo'},inplace=True)

In [50]:
main['id_legajo'] = main['id_legajo'].astype(str)
main['comuna'] = main['comuna'].astype(str)


### Duplicados

Ya teniendo las tablas casi listas. chequeremos si hay duplicados y procederemos a lidiar con ellos

In [51]:
main.duplicated().nunique()

2

In [52]:
main_no_duplicates = main.copy().drop_duplicates(keep='first')

Se econtraron 2 filas repetidas y se elimino una de ellas.

In [53]:
main_no_duplicates[main_no_duplicates.duplicated(['id_legajo'],keep=False)].shape

(42, 8)

Hay 21 legajos duplicados. No los eliminaremos sino que agregaremos prefijos a los id_legajo para mantener toda la data.

In [54]:
nth = ['1-', '2-', '3-', '4-','5-','6-']

def prefix(d):
    n = len(d)
    if n > 1:
        return d.radd([nth[i] for i in range(n)])
    else:
        return d

main_no_duplicates = main_no_duplicates.assign(id_legajo=main_no_duplicates.groupby('id_legajo').id_legajo.transform(prefix))

In [55]:
# comprobamos que no haya legajos duplicados
main_no_duplicates[main_no_duplicates.duplicated(['id_legajo'],keep=False)].head()

Empty DataFrame
Columns: [id_legajo, fecha, franja_horaria, comuna, barrio, lat, long, delito]
Index: []

## Armado de base de datos relacional

Procedemos a armar las tablas de manera que esten relacionadas con sus PK y FK correspondientes

In [56]:
barrios.head()

id_barrio      nombre_barrio id_comuna
0  1          Parque Avellaneda  9       
1  2          Palermo            14      
2  3          Parque Patricios   4       
3  4          Caballito          6       
4  5          Monserrat          1

In [57]:
dict_delitos = dict(zip(delitos['nombre_delito'],delitos['id_delito']))
dict_barrios = dict(zip(barrios['nombre_barrio'],barrios['id_barrio']))

In [58]:
main_no_duplicates['id_delito'] = main_no_duplicates['delito'].map(dict_delitos)
main_no_duplicates['id_barrio'] = main_no_duplicates['barrio'].map(dict_barrios)

In [59]:
main_no_duplicates.drop(columns=['delito','barrio'],inplace=True)

In [60]:
main_no_duplicates['comuna'] = main_no_duplicates['comuna'].astype(float).astype(int)

In [61]:
main_no_duplicates

id_legajo      fecha franja_horaria  comuna         lat  \
0      51585           2016-01-01  13             9      -34.64873     
1      83256           2016-01-01  22             14     -34.576925    
2      117697          2016-01-01  1              4      -34.645197    
3      43088           2016-01-01  19             9      -34.65576     
4      68588           2016-01-01  4              6      -34.624128    
...      ...                  ... ..             ..             ...    
88562  RH-2021-3751758 2021-05-08  10             3       -34,605751   
88563  RH-2021-3768141 2021-06-29  21             14      -34,59266    
88564  RH-2021-3768589 2021-06-30  13             3       -34,608791   
88565  RH-2021-3783716 2021-07-31  1              3       -34,603284   
88566  RH-2021-3807019 2021-10-06  14             1       -34,604575   

             long  id_delito  id_barrio  
0     -58.468536   1          1          
1     -58.4074     1          2          
2     -58.401099   2          3          
3     -58.478681   3          1          
4     -58.436826   4          4          
...          ...  ..         ..          
88562  -58,395375  3          8          
88563  -58,422338  1          2          
88564  -58,404617  1          8          
88565  -58,394526  3          8          
88566  -58,392075  3          17         

[636597 rows x 8 columns]

In [62]:
main_no_duplicates['fecha'].min(), main_no_duplicates['fecha'].max()

(Timestamp('2016-01-01 00:00:00'), Timestamp('2021-12-31 00:00:00'))

Creamos la tabla de dimension 'Fecha'

In [68]:
def create_date_table(start='2016-01-01', end='2021-12-31'):
        df_new = pd.DataFrame({"Date": pd.date_range(start, end)})
        df_new["dia"] = df_new.Date.dt.day
        df_new['dia_nombre'] = df_new['Date'].dt.day_name()
        df_new["mes"] = df_new.Date.dt.month
        df_new['mes_nombre'] = df_new['Date'].dt.month_name()
        df_new["año"] = df_new.Date.dt.year
        return df_new

In [70]:
fecha = create_date_table()
fecha

Date  dia dia_nombre  mes mes_nombre   año
0    2016-01-01  1    Friday     1    January    2016
1    2016-01-02  2    Saturday   1    January    2016
2    2016-01-03  3    Sunday     1    January    2016
3    2016-01-04  4    Monday     1    January    2016
4    2016-01-05  5    Tuesday    1    January    2016
...         ... ..        ...   ..        ...     ...
2187 2021-12-27  27   Monday     12   December   2021
2188 2021-12-28  28   Tuesday    12   December   2021
2189 2021-12-29  29   Wednesday  12   December   2021
2190 2021-12-30  30   Thursday   12   December   2021
2191 2021-12-31  31   Friday     12   December   2021

[2192 rows x 6 columns]

In [71]:
fecha['dia_nombre'] = fecha['dia_nombre'].replace({'Monday':'Lunes', 
                        'Tuesday':'Martes',
                        'Wednesday':'Miercoles', 
                        'Thursday':'Jueves', 
                        'Friday':'Viernes', 
                        'Saturday':'Sabado', 
                        'Sunday':'Domingo'})

In [74]:
fecha['mes_nombre'] = fecha['mes_nombre'].replace({'January':'Enero',
                                'February':'Febrero',   
                                'March':'Marzo',
                                'April':'Abril',
                                'May':'Mayo',
                                'June':'Junio',
                                'July':'Julio',
                                'August':'Agosto',
                                'September':'Septiembre',
                                'October':'Octubre',
                                'November':'Noviembre',
                                'December':'Diciembre'})
                                

In [75]:
fecha

Date  dia dia_nombre  mes mes_nombre   año
0    2016-01-01  1    Viernes    1    Enero      2016
1    2016-01-02  2    Sabado     1    Enero      2016
2    2016-01-03  3    Domingo    1    Enero      2016
3    2016-01-04  4    Lunes      1    Enero      2016
4    2016-01-05  5    Martes     1    Enero      2016
...         ... ..       ...    ..      ...       ...
2187 2021-12-27  27   Lunes      12   Diciembre  2021
2188 2021-12-28  28   Martes     12   Diciembre  2021
2189 2021-12-29  29   Miercoles  12   Diciembre  2021
2190 2021-12-30  30   Jueves     12   Diciembre  2021
2191 2021-12-31  31   Viernes    12   Diciembre  2021

[2192 rows x 6 columns]

In [77]:
main_no_duplicates

id_legajo      fecha franja_horaria  comuna         lat  \
0      51585           2016-01-01  13             9      -34.64873     
1      83256           2016-01-01  22             14     -34.576925    
2      117697          2016-01-01  1              4      -34.645197    
3      43088           2016-01-01  19             9      -34.65576     
4      68588           2016-01-01  4              6      -34.624128    
...      ...                  ... ..             ..             ...    
88562  RH-2021-3751758 2021-05-08  10             3       -34,605751   
88563  RH-2021-3768141 2021-06-29  21             14      -34,59266    
88564  RH-2021-3768589 2021-06-30  13             3       -34,608791   
88565  RH-2021-3783716 2021-07-31  1              3       -34,603284   
88566  RH-2021-3807019 2021-10-06  14             1       -34,604575   

             long  id_delito  id_barrio  
0     -58.468536   1          1          
1     -58.4074     1          2          
2     -58.401099   2          3          
3     -58.478681   3          1          
4     -58.436826   4          4          
...          ...  ..         ..          
88562  -58,395375  3          8          
88563  -58,422338  1          2          
88564  -58,404617  1          8          
88565  -58,394526  3          8          
88566  -58,392075  3          17         

[636597 rows x 8 columns]

## Exportamos los Datasets

In [76]:
with pd.ExcelWriter('Delitos_Caba.xlsx') as writer:
    main_no_duplicates.to_excel(writer, sheet_name='Delitos_CABA',index=False)
    barrios.to_excel(writer,sheet_name='Barrios',index=False)
    comunas.to_excel(writer,sheet_name='Comunas',index=False)
    delitos.to_excel(writer,sheet_name='Delitos',index=False)
    fecha.to_excel(writer,sheet_name='Fecha',index=False)

writer.save()

C:\Users\Nico\anaconda3\lib\site-packages\xlsxwriter\workbook.py:339: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")


## Cambios implementados: 

- Se eliminaron las filas con 'franja_horaria' = 'S/D', 'SD', 'sd'. Aprox 2100 filas
- Se eliminaron las filas con 'barrio' = nan
- En subtipo de lesiones se unificaron los datos. Por ejemplo se paso los femicidios a homicidio doloso, porque solo hay datos de femicidios de un solo año, lo mismo con los transvesticidios. Los robos con moto se los pone como roobo con violencia, etc
- Se corrigieron algunas inconsistencias en los datos de diferentes años, por ejemplo barrios ingresados de manera distinta (La Paternal, Paternal)
- Se unificaron las tablas 'tipo delito' y 'subtipo delito' en delito
- Se creo una columna con el dia de la semana
- La columna 'cantidad_registrada', en la fuente de los datos no se especifica bien su significado
- Implementacion de las FK en la tabla de hechos asociadas a las PK de las tablas de dimensiones
